name: Forge Coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

permissions: write-all

jobs:
  check:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: Run coverage
        env:
          MNEMONIC: ${{ secrets.MNEMONIC_FOR_TESTS }}
        run: |
          forge coverage --report lcov && lcov --extract lcov.info -o lcov.info 'src/*'
        id: coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          artifact-name: code-coverage-report
          minimun-coverage: 100
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
